TheRandomLabs/scoop-nonportable

virtualbox-np.json
VirtualBox: Update to version 5.2.20
=> VirtualBox: Update to version 5.2.20

k-lite-codec-pack-basic-np.json, k-lite-codec-pack-full-np.json, k-lite-codec-pack-mega-np.json, k-lite-codec-pack-standard-np.json, nodejs-np.json, notepadplusplus-np.json, pgadmin4-np.json, virtualbox52-np.json, winfsp-np.json
* Fixed WinFSP autoupdate
* Fixed Notepad++ checksum file detection for autoupdate
* K-Lite Codec Pack Basic 14.9.0
* K-Lite Codec Pack Standard 14.9.0
* K-Lite Codec Pack Full 14.9.0
* K-Lite Codec Pack Mega 14.9.0
* NodeJS 11.14.0
* Notepad++ 7.6.6
* PGAdmin 4.5
* VirtualBox (5.2) 5.2.28
* WinFSP 1.4.19049
=> Updates and fixes

notepadplusplus-np.json, sshfs-np.json, virtualbox-np.json, virtualbox52-np.json, winfsp-np.json
=> SSHFS manifest fix, VirtualBox reboot fix and pkgs updates

vmware-horizon-client-np.json
https://docs.vmware.com/en/VMware-Horizon-Client-for-Windows/5.1/rn/horizon-client-windows-51-release-notes.html
=> vmware-horizon-client-np: Update to version 5.1.0

virtualbox-np.json
Update virtualbox-np version to the newest version 6.0.10.
=> Update virtualbox version to 6.0.10

virtualbox-np.json
Updating virtualbox-np 6.0.10 -> 6.0.12
=> Update virtualbox-np to 6.0.12

vmware-horizon-client-np.json
[VMware Horizon Client 5.2 for Windows Release Notes](https://docs.vmware.com/en/VMware-Horizon-Client-for-Windows/5.2/rn/horizon-client-windows-52-release-notes.html)
=> vmware-horizon-client-np: Update to version 5.2.0

sql-server-management-studio-np.json
[SQL Server Management Studio 18.3 (15.0.18178.0) release notes](https://docs.microsoft.com/en-us/sql/ssms/release-notes-ssms?view=sql-server-2017#ssms-183)
=> sql-server-management-studio-np: Update to version 15.0.18178.0

teamviewer-np.json
=> teamviewer-np: fix hash

sql-server-management-studio-np.json
[Release notes for SQL Server Management Studio 18.3.1](https://docs.microsoft.com/en-us/sql/ssms/release-notes-ssms?view=sql-server-2017#ssms-1831)
=> sql-server-management-studio-np: Update to version 15.0.18183.0

virtualbox-np.json
Bringing latest maintenance 6.0.14 version to virtualbox-np
=> Update virtualbox-np to 6.0.14

logitech-gaming-software-np.json
Logitech Gaming Software allows for the customization of functions on Logitech gaming mice, keyboards, headsets, speakers and wheels. An autoupdate is not available as Logitech doesn't seem to consistently place the latest version in the right place.
=> Add Logitech Gaming Software

virtualbox-np.json
I fixed Scoop not being able to complete the installation and uninstallation of VirtualBox when not running as administrator. I also removed the start menu and desktop shortcuts that the installer creates. :)
=> VirtualBox improvements

8gadgetpack-np.json
**8GadgetPack** ([link](https://8gadgetpack.net/)) is a software that enables desktop gadgets and sidebar for Windows 10/8.1/7.
=> 8GadgetPack-np: Add version 31.0

bluestacks-np.json
[BlueStacks](https://www.bluestacks.com/) is an Android emulator.
=> BlueStacks-np: Add version 4.140

veyon-np.json
**Veyon** ([link](https://veyon.io/)) is a computer monitoring / classroom management software.
(Requested in lukesampson/scoop-extras#2798)
=> veyon-np: Add version 4.3.0.0

sql-server-management-studio-np.json
[Release notes for SQL Server Management Studio 18.4](https://docs.microsoft.com/en-us/sql/ssms/release-notes-ssms?view=sql-server-2017#ssms-184)
=>  sql-server-management-studio-np: Update to version 15.0.18206.0

biglybt.json
An open source torrent client based on Azureus.
=> Add Biglybt

microsoft-edge-beta-np.json, microsoft-edge-dev-np.json
=> Add Microsoft Edge Beta and Dev

bucket/fluent-terminal-np.json
https://github.com/felixse/FluentTerminal/issues/383
=> Add fluent-terminal

bucket/workman-np.json, bucket/workman-p-np.json, bucket/workman-p-uk-np.json, bucket/workman-uk-np.json
Includes layouts for US, US Programmer, UK, and UK Programmer.
=> Workman keyboard layouts.

bucket/teamviewer-np.json
The procedures I have reviewed were not working. I think it is the repo's problem. In addition, I cannot open an issue so I need to submit a pull request directly.
=> Update for hash check failure

bucket/vmware-horizon-client-np.json
[VMware Horizon Client 5.4 for Windows Release Notes](https://docs.vmware.com/en/VMware-Horizon-Client-for-Windows/5.4/rn/horizon-client-windows-54-release-notes.html)
=> vmware-horizon-client-np: Update to version 5.4.0-15805437

bucket/vmware-horizon-client-np.json
[VMware Horizon Client 5.4.1 for Windows Release Notes](https://docs.vmware.com/en/VMware-Horizon-Client-for-Windows/5.4.1/rn/horizon-client-windows-541-release-notes.html)
=> vmware-horizon-client-np: Update to version 5.4.1-15897311

bucket/vmware-horizon-client-np.json
[VMware Horizon Client 5.4.2 for Windows Release Notes](https://docs.vmware.com/en/VMware-Horizon-Client-for-Windows/5.4.2/rn/horizon-client-windows-542-release-notes.html)
Actually released and downloadable but their download page is not up to date.
=> vmware-horizon-client-np: Update to version 5.4.2-15936851

bucket/virtualbox-np.json
virtualbox-np: Update to 6.1.8
=> virtualbox-np: Update to 6.1.8

bucket/virtualbox-with-extension-pack-np.json
virtualbox-with-extension-pack-np: Update to 6.1.8
=> virtualbox-with-extension-pack-np: Update to 6.1.8

bucket/auto-dark-mode-np.json
#172 was a good catch, but it's only a partial fix.
=> auto-dark-mode-np: fix install

bucket/wireguard-np.json
=> wireguard-np: Add version 0.1.1

bucket/vmware-horizon-client-np.json
[VMware Horizon Client for Windows 2006 Release Notes](https://docs.vmware.com/en/VMware-Horizon-Client-for-Windows/2006/rn/horizon-client-windows-2006-release-notes.html)
=> vmware-horizon-client-np: Update to 2006-8.0.0-16531419

bucket/virtualbox-with-extension-pack-np.json
Fix version/hash for extension pack
=> virtualbox-with-extension-pack-np: Update to version 6.1.16

bucket/zadig-np.json
=> zadig: fix autoupdate $version

bucket/vmware-horizon-client-np.json
I was actually having stability problems with 8.0.0 which 8.1.0 seems to fix.
=> vmware-horizon-client-np: Update to 2012-8.1.0-17349995

bucket/omnidb-np.json
* lukesampson/scoop-extras#5947
This doesn't seem like it has a portable installation available so I'm submitting here.
If there's anything to improve in this recipe, please let me know.
=> omnidb-np: Add version 2.17.0
