virtualbox-np.json

there is an additional commit to fix the autoupdate, since the request "https://update.virtualbox.org/query.php?platform=WINDOWS_64BITS_GENERIC&version=0.0.0" still reports 5.2.24-128163 as the latest version.

update virtualbox to 6.0.2

---

sshfs-np.json
winfsp-np.json

Previous WinFSP manifest was fetching the wrong resource from GitHub artifacts. Also removed installer/uninstaller declarations since scoop [discovers MSI installers by default](https://github.com/lukesampson/scoop/wiki/App-Manifests#Optional%20Properties).
[SSHFS-Win](https://www.github.com/billziss-gh/sshfs-win) is another utility by [Bill Zissimopoulos](https://www.github.com/billziss-gh) that depends on WinFSP.

Fix WinFSP manifest, add SSHFS-Win

---

vmware-horizon-client-np.json

Add manifest for VMware Horizon Client 5.0.0. Some notes:
- Installer/uninstaller requires elevation, wasn't able to get it working without UAC prompt.
- Installer sets permissions on the directory passed with `INSTALLDIR`, which caused problems when scoop tried to create `install.json` and `manifest.json` files in non-elevated shell. Specified install directory as `$dir\files` to workaround the problem. 
- Wasn't able to figure out a working `checkver`/`autoupdate` strategy based on the ever-changing `downloadGroup` in VMware download page (ex. compare URLs for [4.10.0] and [5.0.0])
Please take a look, any comments or suggestions welcome!
[4.10.0]: https://my.vmware.com/web/vmware/details?productId=578&rPId=29501&downloadGroup=CART19FQ4_WIN_410
[5.0.0]: …

Add VMware Horizon Client manifest

---

vmware-horizon-client-np.json

<pre><code>PS> scoop cleanup vmware-horizon-client-np
Removing vmware-horizon-client-np: 5.0.0-12606690
Remove-Item : Access to the path 'C:\Users\name\scoop\apps\vmware-horizon-client-np\5.0.0-12606690\files' is denied.
At C:\Users\name\scoop\apps\scoop\current\libexec\scoop-cleanup.ps1:51 char:9
+         Remove-Item $dir -ErrorAction Stop -Recurse -Force
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : PermissionDenied: (C:\Users\name\sc\u2026.0.0-12606690\files:DirectoryInfo) [Remove-Item], UnauthorizedAccessException
+ FullyQualifiedErrorId : RemoveFileSystemItemUnAuthorizedAccess,Microsoft.PowerShell.Commands.RemoveItemCommand
</code></pre>
During install, a subdirectory of scoop application version `$dir` is defined to workaround an issue with …

Fix incomplete cleanup/uninstall of VMware Horizon Client

---

sshfs-np.json
winfsp-np.json

close #41 
Notes:
* I tried using `sudo` and `Invoke-ExternalCommand -RunAs` for installer script, so that an **UAC prompt** will pop up when user is not running the terminal under Admin. Unfortunately none of them worked for `msiexec`.
* I am not familiar with how `sshfs` works. Is it better to add some items into `bin` or `shortcuts`?

sshfs-np, winfsp-np: Install MSI packages (instead of extracting them)

---

sql-server-management-studio-np.json

Add manifest for [SQL Server Management Studio](https://docs.microsoft.com/en-us/sql/ssms/download-sql-server-management-studio-ssms). Some notes:
- Installer/uninstaller requires elevation, wasn't able to get it working without UAC prompt.
- If install/uninstall fails, call scoop `abort` with message pointing to log file for details
- `checkver` should be working, haven't been able to figure out `autoupdate` based on the difference between release label (e.g. 18.2) and version number
Please take a look, any comments or suggestions welcome. Thanks!

Add SQL Server Management Studio manifest

---

teamviewer-np.json

This adds non-portable version of **TeamViewer**.
Some of **TeamViewer**'s function (such as "keep logged in" or "Grand Easy Access") only works when the user installs TeamViewer with the installer.
(see: https://github.com/lukesampson/scoop-extras/issues/2604)

teamviewer-np: Add version 14.4.2669

---

virtualbox-np.json
virtualbox52-np.json

Since I'm using a lot of the commandline tools for configurations via scripts, it's really helpful to call the executable by their name directly.
By the way, would you prefer that we make the `virtualbox52-np` and `virtualbox-np` able to coexists?
If so, I can update the PR by doing something like this on `virtualbox52-np.json`:
```
...
"bin": [
[
"VBoxBalloonCtrl.exe",
"VBoxBalloonCtrl52"
],
[
"VBoxBugReport.exe",
"VBoxBugReport52"
],
...
],
...
```
Thanks!

Include `bin` and `shortcuts` to VirtualBox manifests.

---

notepadplusplus-np.json

close #69
* Update the package (version 7.8 -> 7.8.1)
* Use `Invoke-ExternalCommand` instead of running the installer directly. When the user installs the package without admin rights, the program will show a **UAC popup** to acquire admin rights. (instead of showing error messages and abort installation, like the case described in #69)
* Remove the argument `allowAppDataPluginsLoading` of the installer since [it is no longer in use](https://github.com/notepad-plus-plus/notepad-plus-plus/commit/113212547fcf89ac302ec35839bac109995ee1fa)
* Remove **notes**. (Context menu is already added in the **nonportable** version. No need to show the message.)
* Restart `explorer.exe` after running the uninstaller. This will avoid the **file in use** error during uninstall. (The file is actually …

Notepad++: some minor fixes

---

darktable-np.json

We already have `darktable` package in the extras bucket. However, The developer does not provide portable ZIP after version `2.4.5`, and the installer cannot be properly extracted by 7-zip. This provides a **temporary solution** for those who want newer versions.
For details, see:
https://github.com/lukesampson/scoop-extras/issues/1831
https://github.com/darktable-org/darktable/issues/2908
https://github.com/lukesampson/scoop-extras/issues/2308 (Outstanding Excavator issues)

darktable-np: add version 2.6.3

---

bucket/vmware-horizon-client-np.json

Add support for [checkver and autoupdate](https://github.com/lukesampson/scoop/wiki/App-Manifest-Autoupdate#using-checkverps1-to-query-and-autoupdate) to simplify maintenance of
`vmware-horizon-client-np` manifest. Have not found a central registry for
VMware Horizon Client versions, so the `downloadGroup` parameter in
`checkver.url` requires manual update.
Due to the manual update requirement for download group with each minor
release, unsure if this makes the `checkver` and `autoupdate` worth it.
If nothing else this helps prevent typos in version or hash.

vmware-horizon-client-np: add checkver, autoupdate

---

bucket/sshfs-np.json
bucket/winfsp-np.json

`Invoke-ExternalCommand ... -RunAs` works properly after https://github.com/lukesampson/scoop/pull/3547. 
(Will popup an **UAC prompt** when not running under Admin rights) 
Therefore, the tweak in `pre_install` section is not needed anymore.

sshfs-np, winfsp-np: Modify installer

---

bucket/fluent-terminal-np.json

After installation, it asks 'Press Enter to continue'. Adding a -Force flag to post-install script seems to remove that prompt.

fluent-terminal : Remove prompt after installation

---

bucket/fman-np.json

* The installer(setup.exe) automatically opens *fman* (as a child process of the installer) before closing. This **installer.script** deals with the problem.
* Change license URL from `https://fman.io/buy` to `https://fman.io/legal`.

fman-np: installer tweaks

---

bucket/lantern-client-np.json
bucket/lantern-np.json

This package is added because the installer of **lantern-client** cannot be properly extracted after version 5.5.6.
Also see:
https://github.com/lukesampson/scoop-extras/issues/3581
https://github.com/lukesampson/scoop-extras/pull/3583

lantern-client-np: Add version 5.8.1

---

bucket/google-japanese-input-np.json

**Google Japanese Input** ([homepage](https://www.google.co.jp/ime/)) ([Wikipedia](https://en.wikipedia.org/wiki/Google_Japanese_Input)) is a Japanese input method (IME) published by Google.
Notes:
* **checkver**: I couldn't find an official page that has the **latest version number**. Therefore I use a third-party website instead. Is this acceptable?

google-japanese-input-np: Add version 2.25.3700.0

---

bucket/lightscribe-system-software-np.json

**LightScribe System Software** ([homepage](https://lightscribesoftware.org/lightscribe-system-software/)) is the software required for LightScribe disk drives to work. (also called LightScribe drivers)
Notes:
* *checkver/autoupdate* is not needed because *LightScribe System Software* has not been updated since 2013.
* The license can be found in `license.rtf` under installation path.
* *LightScribe System Software* is installed at `$Env:PROGRAMFILES(X86)\Common Files` on 64-bit machines, but it's `$Env:PROGRAMFILES\Common Files` on 32-bit machines. Therefore I keep the original installer (`LS_HSI.msi`) to avoid tricky situations for **uninstalling**.

lightscribe-system-software-np: Add version 1.18.27.10

---

bucket/lightscribe-system-software-np.json

Should be LightScribe disc drive, not "disk" drive. Sorry for the stupid mistake.

lightscribe-system-software-np: Fix typo

---

bucket/notepadplusplus-np.json

mentioned in https://github.com/TheRandomLabs/scoop-nonportable/issues/69#issuecomment-595703511.
The installer/uninstaller of **Notepad++** will reset user settings (stored in `$Env:AppData\Notepad++`) when silent switch (`/S`) is applied. This causes **user settings lost** when the user updates *Notepad++* through Scoop.
This solves the issue by copying the user settings folder during install/uninstall.

notepadplusplus-np: keep user settings during update

---

bucket/winbtrfs-np.json

**WinBtrfs** ([Github repo](https://github.com/maharmstone/btrfs)) is a Windows driver for the next-generation Linux filesystem *Btrfs*.
Notes:
* This manifest follows the pattern of [VCRedist packages](https://github.com/lukesampson/scoop-extras/blob/master/bucket/vcredist2019.json).
* The "signing error problem" is described the [readme file](https://github.com/maharmstone/btrfs#installation).

winbtrfs-np: Add version 1.7.1

---

bucket/mactype-np.json

**MacType**([Github repo](https://github.com/snowie2000/mactype)) is a tool that provides better font rendering for Windows.
Notes:
* This package is sent to here (instead of the *extras* bucket) because **MacType** involves too many system tweaking, which does not meet the criteria of the *extras* bucket.
* I use the "beta version" because "stable version" has not been updated for 2 years. Also, the installer used in newer versions is different from the older versions. Using newer ones can avoid future maintainance issues.
* The *notes* are written according to [known issues](https://github.com/snowie2000/mactype#known-issues) and [developer's reply about the uninstallation problem](https://github.com/snowie2000/mactype/issues/133).

mactype-np: Add version 2019.1-beta6

---

bucket/mactype-np.json

Universal extractor 2 just runs innounp to extract the installer, since scoop installs and uses innounp from the main bucket anytime the user installs something with `"innosetup": true` I cut out the middle man. Works with no tweaks needed.

mactype-np: Remove uniextract2 dependency, simplify manifest 

---

bucket/fluent-terminal-np.json

Seems like everything regarding the installation of Fluent Terminal has been changed. You just need to run the appxbundle file now.

Update fluent-terminal-np.json to 0.7.0.0 and new manifest

---

bucket/sql-server-management-studio-np.json

Append download url with `#/<InstallerName>` syntax as described in the [`url`](https://github.com/lukesampson/scoop/wiki/App-Manifests#optional-properties) section. Required to rename file to `SSMS-Setup-ENU.exe` on download, which is required by installer script.

sql-server-management-studio-np: Fix download

---

bucket/barrier-np.json
bucket/barrier.json

Barrier is a fork of Synergy that focuses on stability and being simple
and free.
This installer is not completely hands-off. It requires permission
elevation because it needs to take control of your mouse (client) or add
a virtual monitor (server). The Barrier installer also asks to install
Bonjour (for discovery). It installs into Program Files. Seems like
nonportable is the right bucket.
This json is based on:
https://gist.github.com/pluser/239add9975080a01e2bb93b28e174acb
I changed the description and formatting.

barrier: setup barrier virtual kvm

---

bucket/notepads-np.json

The certificate import was throwing an error(in the latest version), so I changed it.
Settings are backed up during uninstallation from persistent directory and copied during post install to %LocalAppData%\Packages\*PackagaFamilyName*\Settings.
I removed the shim because notepads already has it. UWP apps have a way of shimming themselves. But since %LocalAppData%\Microsoft\WindowsApps was not in my path, so I didnt know. Windows Terminal also uses this feature.
From the github page
- Launch from the command line or PowerShell by typing: `notepads` or `notepads %FilePath%.`
Also uninstaller force closes the app, otherwise it may cause errors while backing up settings.

Notepads-np - Persistent Settings, install certificate without error and more

---

bucket/fluent-terminal-np.json

Settings are backed up during uninstallation from persistent directory and copied during post install to %LocalAppData%\Packages*PackagaFamilyName*\Settings.
I removed the shim because notepads already has it. UWP apps have a way of shimming themselves. But since %LocalAppData%\Microsoft\WindowsApps was not in my path, so I didnt know. Windows Terminal also uses this feature. In this case you have to type `flute` in your console
Also uninstaller force closes the app, otherwise it may cause errors while backing up settings.

Fluent-Terminal : Persistent settings and more

---

bucket/fluent-terminal-np.json

The app will now globally install for all users(uninstall was already global). Although a minimum 2 seconds waiting needs to be added to the script, otherwise post-install wont persist settings(it would still be installing in the background).
Taskill will throw an error if app is not opened, so I removed it. If anyone uses this app, they should close it and then close the tray icon before uninstalling or updating, otherwise settings will not persist.

Fluent-terminal-np - Global Install

---

bucket/notepads-np.json

The app will now globally install for all users(uninstall was already global). Although a minimum 2 seconds waiting needs to be added to the script, otherwise post-install wont persist settings(it would still be installing in the background).
Taskill will throw an error if app is not opened, so I removed it. Its a given that you are supposed to close an app during update or uninstall(in this case it wont persist settings).

Notepads-np - Global install for all users

---

bucket/mactype-np.json

It may not make sense to persist some `nonportable` app's file, but MacType is portable to some extent, so here it is. Feel free to close this if you find it inappropriate.

mactype-np: Add persist

---

bucket/flash-drive-tester-np.json

**Flash Drive Tester** ([homepage](https://www.vconsole.com/download)) allows testing of any removable media including SD, CF, USB flash drives for bad or unstable sectors. Especially useful for testing for fake sizes often seen on low quality USB flash drives.
Notes:
* This package is sent here (instead of the [extra bucket](https://github.com/lukesampson/scoop-extras/)) because the MSI installer cannot be properly extracted using *7-zip* or *lessmsi*.
* *checkver/autoupdate* is not needed because *Flash Drive Tester* has not been updated since 2009.

flash-drive-tester-np: Add version 1.14

---

bucket/anki-np.json

This adds a non portable version as the version in [extras](https://github.com/lukesampson/scoop-extras/blob/master/bucket/anki.json) uses many tricks in order to use a persist folder, which makes it clunky to use (cmd shell at startup, which is incidentally less responsive).
The only issue with this NP version is that the uninstaller does not use the /S flag, which I let it anyway as it may change in the future. The installation is correctly silent however.

anki-np: Add version 2.1.26

---

bucket/nvidia-display-driver-dch-np.json
bucket/nvidia-display-driver-dch-with-3d-vision-np.json

This would fix #162 .
This also includes fixes for the manifest, as `Get-WMIObject` is deprecated since PowerShell 3, and not compatible with PowerShell>5. `Move-Item "$dir\*" -Destination "$dir\extract"` was also trying to move the extract dir into itself so I fixed it.
I can make another PR to fix them on the non-DCH driver variants too.

nvidia-display-driver: Add DCH variants

---

bucket/nvidia-display-driver-np.json
bucket/nvidia-display-driver-with-3d-vision-np.json

As explained in PR #164 , this fixes the install scripts for `nvidia-display-driver-np` and `nvidia-display-driver-with-3d-vision-np`.

nvidia-display-driver: Fix install script

---

bucket/nvidia-display-driver-dch-np.json
bucket/nvidia-display-driver-dch-with-3d-vision-np.json

It seems like I had forgotten to correct the links in the autoupdate parts of the DCH drivers. It is fixed here.

nvidia-display-driver-dch: Fix autoupdate

---

bucket/auto-dark-mode-np.json

There is a slight mismatch on the file version and the release version (which is still 3.0 on GitHub) but I'm hopeful that future versions won't need much manual intervention based on https://github.com/Armin2208/Windows-Auto-Night-Mode/issues/156#issuecomment-669930262

auto-dark-mode-np: Update to version 3.0.1

---

bucket/zadig-np.json

**Zadig** ([homepage](https://zadig.akeo.ie/)) is a Windows application that installs generic USB drivers, such as WinUSB, libusb-win32/libusb0.sys or libusbK, to help you access USB devices.
Notes:
* This package is sent here (instead of the [extras bucket](https://github.com/lukesampson/scoop-extras/)) because Zadig involves **driver installation** or **system tweaks**, which does not meet the criteria of the extras bucket.
* The **pre_install** script will set Zadig's built-in update as "disabled". (It is better to manage updates by Scoop)
* **persist** is not needed because Zadig stores its config data at `HKCU:\SOFTWARE\Akeo Consulting\Zadig`.
Please tell me if there is any problem. Thanks.

zadig-np: Add version 2.5

---

bucket/equalizer-apo-np.json

Requested in lukesampson/scoop-extras#4018
**Equailzer APO** ([homepage](https://sourceforge.net/projects/equalizerapo/)) is a parametric/graphic equalizer.
Notes:
* **installation path**: The installer is created with NSIS. I tried putting `/D=$dir` in the arguments, but it seems not working.
Also, the benchmark program (`benchmark.exe`) only reads config from `C:\Program Files\EqualizerAPO\config\config.txt`. Modifying the path will cause error.
* **persist** is not needed because the installer/uninstaller of Equalizer APO will not delete the config files. (which are under the `config` folder of the installation path)
Please tell me if there is any problem. Thanks.

equalizer-apo-np: Add version 1.2.1

---

bucket/equalizer-apo-np.json

This will remove the unnecessary `/D=$dir` in *installer.script*. 
I didn't notice it when sending the PR. Sorry.

equalizer-apo-np: Clean installer.script

---

bucket/xampp-np.json

requested in lukesampson/scoop-extras#3570
**XAMPP**([homepage](https://www.apachefriends.org/)) is an Apache distribution containing MariaDB, PHP, and Perl.
Notes:
* The Portable Version of XAMPP does not contain *FileZilla FTP* and *Mercury Mail Server*. (The service installations are also disabled). Non-portable version contains all the components.
* **XAMPP** installs at `C:\xampp` by default. Running the installer with `--help` will show available parameters. However `--prefix $dir` doesn't seem to work. The NSIS script (extracted from the installer) shows that install path is "hardcoded" as `C:\xampp`.
[xampp.nsi.txt](https://github.com/TheRandomLabs/scoop-nonportable/files/5136036/xampp.nsi.txt)
* I tried creating a **symbolic link** at `C:\xampp` that points to …

xampp-np: Add version 7.4.8-0

---

bucket/winbtrfs-np.json

PnPUtil exits with code 3010 when the installation was successful but
needs a reboot to finalize [1].
This adds the appropriate -ContinueExitCodes option to the installer and
uninstaller scripts.
[1]: https://docs.microsoft.com/en-us/windows-hardware/drivers/devtest/pnputil-return-values

winbtrfs-np: Handle non-zero success exit code

---

bucket/powertoys-np.json

Rewrite the config for the .exe installer. Without arguments, currently, I cannot change the original inst dir to the scoop dir. Test on Windows 10 Pro Ver.19042.

Update powertoys-np to 0.25.0

---

bucket/dokany-np.json

Thought this might be useful (I need it for https://github.com/bailey27/cppcryptfs).
Do you know if I can open a PR to include a manifest for cppcryptfs into the scoop-extras bucket and make it depend on dokany-np?

dokany-np: Add version 1.4.0.1000

---

bucket/anki-np.json

Since Anki 2.1.36, 32 bits builds are not supported (see [here](https://changes.ankiweb.net/#/?id=changes-in-2136)). This PR removes the 32 bits architecture from the manifest so that it can continue to get updated.

anki-np: remove 32 bit and update to 2.1.37

---

bucket/dokany-np.json

The dokany.inf file does not correctly install the dokan1.sys and dokan1.dll files to %WINDIR%/system32.
It erroneously worked for me because I had installed dokany manually some time before installing via scoop.

dokany-np: Fix installer by using the msi packages

---

bucket/cppcryptfs-np.json

This package was not accepted in the scoop-extras bucket because of the dependency on dokany-np (https://github.com/lukesampson/scoop-extras/pull/5305).
This is actually a portable app but I still added the `-np` suffix because all other apps in the bucket have it.

cppcryptfs-np: Add version 1.4.3.5

---

bucket/teamviewer-np.json

The `autoupdate`'s url renaming is not consist with original installer script.
Plus, I deleted the code of removing teamviewer start menu shortcut. I prefer a start menu shortcut than a desktop shortcut. But that part may be approved in some other ways, too.

Fix teamviewer-np.json autoupdate

---

bucket/powertoys-np.json

* closes #227 
`Get-WmiObject` is now deprecated and powertoys doesn't come with an uninstaller executable nor does it have a `.uninstall()` method.
Also, my first try was using `Get-CimInstance` but I thought "Hey that's super slow", so I'm proposing this script:
- Get the uninstallable softwares through the registry
- Filter out the PowerToys entry
- Isolate the UninstallString and replace `/I` by `/x`
- Execute the resulting command
Unfortunately, I've been struggling to make the uninstall quiet,
I tried `/qn`, `/passive` and `/quiet` but it just gives me an error,
so if someone more knowledgable has any suggestion, please let me know.

powertoys-np: Fix uninstall script
